name: My Workflow

on:
  push:
    paths:
      - package.json
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jaliborc/action-general-autotag@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source_file: "package.json"
          extraction_regex: "\\s*\"version\"s*:\\s*\"([\\d\\.]+)\""
